FROM golang:1.26@sha256:313faae491b410a35402c05d35e7518ae99103d957308e940e1ae2cfa0aac29b AS builder
ARG VERSION=dev
ARG TARGETOS
ARG TARGETARCH
WORKDIR /workspace
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS="${TARGETOS}" GOARCH="${TARGETARCH}" \
  go build -ldflags "-s -w -X github.com/avodah-inc/crossplane-provider-slack/internal/version.Version=${VERSION}" \
  -o /usr/local/bin/provider ./cmd/provider-usergroup/

FROM gcr.io/distroless/static:nonroot@sha256:e3f945647ffb95b5839c07038d64f9811adf17308b9121d8a2b87b6a22a80a39
COPY --from=builder /usr/local/bin/provider /usr/local/bin/provider
COPY package/usergroup/crossplane.yaml /package.yaml
COPY package/usergroup/crds/ /crds/
USER 65532:65532
ENTRYPOINT ["provider"]
