FROM golang:1.27@sha256:512690a5660563b57d37ecc31129e7f136e831db2aed24a1dbeb8ad7380dc0fa AS builder
ARG VERSION=dev
ARG TARGETOS
ARG TARGETARCH
WORKDIR /workspace
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS="${TARGETOS}" GOARCH="${TARGETARCH}" \
    go build -ldflags "-s -w -X github.com/avodah-inc/crossplane-provider-slack/internal/version.Version=${VERSION}" \
    -o /usr/local/bin/provider ./cmd/family-provider/

FROM gcr.io/distroless/static:nonroot@sha256:e3f945647ffb95b5839c07038d64f9811adf17308b9121d8a2b87b6a22a80a39
COPY --from=builder /usr/local/bin/provider /usr/local/bin/provider
COPY package/family/package.yaml /package.yaml
USER 65532:65532
ENTRYPOINT ["provider"]
