//go:build !ignore_autogenerated

/*
Copyright 2024 Avodah Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConversationBookmark) DeepCopyInto(out *ConversationBookmark) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConversationBookmark.
func (in *ConversationBookmark) DeepCopy() *ConversationBookmark {
	if in == nil {
		return nil
	}
	out := new(ConversationBookmark)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConversationBookmark) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConversationBookmarkList) DeepCopyInto(out *ConversationBookmarkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConversationBookmark, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConversationBookmarkList.
func (in *ConversationBookmarkList) DeepCopy() *ConversationBookmarkList {
	if in == nil {
		return nil
	}
	out := new(ConversationBookmarkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConversationBookmarkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConversationBookmarkObservation) DeepCopyInto(out *ConversationBookmarkObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConversationBookmarkObservation.
func (in *ConversationBookmarkObservation) DeepCopy() *ConversationBookmarkObservation {
	if in == nil {
		return nil
	}
	out := new(ConversationBookmarkObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConversationBookmarkParameters) DeepCopyInto(out *ConversationBookmarkParameters) {
	*out = *in
	if in.ConversationID != nil {
		in, out := &in.ConversationID, &out.ConversationID
		*out = new(string)
		**out = **in
	}
	if in.ConversationRef != nil {
		in, out := &in.ConversationRef, &out.ConversationRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ConversationSelector != nil {
		in, out := &in.ConversationSelector, &out.ConversationSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConversationBookmarkParameters.
func (in *ConversationBookmarkParameters) DeepCopy() *ConversationBookmarkParameters {
	if in == nil {
		return nil
	}
	out := new(ConversationBookmarkParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConversationBookmarkSpec) DeepCopyInto(out *ConversationBookmarkSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConversationBookmarkSpec.
func (in *ConversationBookmarkSpec) DeepCopy() *ConversationBookmarkSpec {
	if in == nil {
		return nil
	}
	out := new(ConversationBookmarkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConversationBookmarkStatus) DeepCopyInto(out *ConversationBookmarkStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConversationBookmarkStatus.
func (in *ConversationBookmarkStatus) DeepCopy() *ConversationBookmarkStatus {
	if in == nil {
		return nil
	}
	out := new(ConversationBookmarkStatus)
	in.DeepCopyInto(out)
	return out
}
