//go:build !ignore_autogenerated

/*
Copyright 2024 Avodah Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConversationPin) DeepCopyInto(out *ConversationPin) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConversationPin.
func (in *ConversationPin) DeepCopy() *ConversationPin {
	if in == nil {
		return nil
	}
	out := new(ConversationPin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConversationPin) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConversationPinList) DeepCopyInto(out *ConversationPinList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConversationPin, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConversationPinList.
func (in *ConversationPinList) DeepCopy() *ConversationPinList {
	if in == nil {
		return nil
	}
	out := new(ConversationPinList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConversationPinList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConversationPinObservation) DeepCopyInto(out *ConversationPinObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConversationPinObservation.
func (in *ConversationPinObservation) DeepCopy() *ConversationPinObservation {
	if in == nil {
		return nil
	}
	out := new(ConversationPinObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConversationPinParameters) DeepCopyInto(out *ConversationPinParameters) {
	*out = *in
	if in.ConversationID != nil {
		in, out := &in.ConversationID, &out.ConversationID
		*out = new(string)
		**out = **in
	}
	if in.ConversationRef != nil {
		in, out := &in.ConversationRef, &out.ConversationRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ConversationSelector != nil {
		in, out := &in.ConversationSelector, &out.ConversationSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConversationPinParameters.
func (in *ConversationPinParameters) DeepCopy() *ConversationPinParameters {
	if in == nil {
		return nil
	}
	out := new(ConversationPinParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConversationPinSpec) DeepCopyInto(out *ConversationPinSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConversationPinSpec.
func (in *ConversationPinSpec) DeepCopy() *ConversationPinSpec {
	if in == nil {
		return nil
	}
	out := new(ConversationPinSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConversationPinStatus) DeepCopyInto(out *ConversationPinStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConversationPinStatus.
func (in *ConversationPinStatus) DeepCopy() *ConversationPinStatus {
	if in == nil {
		return nil
	}
	out := new(ConversationPinStatus)
	in.DeepCopyInto(out)
	return out
}
