//go:build !ignore_autogenerated

/*
Copyright 2024 Avodah Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConversationMember) DeepCopyInto(out *ConversationMember) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConversationMember.
func (in *ConversationMember) DeepCopy() *ConversationMember {
	if in == nil {
		return nil
	}
	out := new(ConversationMember)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConversationMember) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConversationMemberList) DeepCopyInto(out *ConversationMemberList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConversationMember, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConversationMemberList.
func (in *ConversationMemberList) DeepCopy() *ConversationMemberList {
	if in == nil {
		return nil
	}
	out := new(ConversationMemberList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConversationMemberList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConversationMemberObservation) DeepCopyInto(out *ConversationMemberObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConversationMemberObservation.
func (in *ConversationMemberObservation) DeepCopy() *ConversationMemberObservation {
	if in == nil {
		return nil
	}
	out := new(ConversationMemberObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConversationMemberParameters) DeepCopyInto(out *ConversationMemberParameters) {
	*out = *in
	if in.ConversationID != nil {
		in, out := &in.ConversationID, &out.ConversationID
		*out = new(string)
		**out = **in
	}
	if in.ConversationRef != nil {
		in, out := &in.ConversationRef, &out.ConversationRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ConversationSelector != nil {
		in, out := &in.ConversationSelector, &out.ConversationSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.UserEmail != nil {
		in, out := &in.UserEmail, &out.UserEmail
		*out = new(string)
		**out = **in
	}
	if in.UserID != nil {
		in, out := &in.UserID, &out.UserID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConversationMemberParameters.
func (in *ConversationMemberParameters) DeepCopy() *ConversationMemberParameters {
	if in == nil {
		return nil
	}
	out := new(ConversationMemberParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConversationMemberSpec) DeepCopyInto(out *ConversationMemberSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConversationMemberSpec.
func (in *ConversationMemberSpec) DeepCopy() *ConversationMemberSpec {
	if in == nil {
		return nil
	}
	out := new(ConversationMemberSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConversationMemberStatus) DeepCopyInto(out *ConversationMemberStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConversationMemberStatus.
func (in *ConversationMemberStatus) DeepCopy() *ConversationMemberStatus {
	if in == nil {
		return nil
	}
	out := new(ConversationMemberStatus)
	in.DeepCopyInto(out)
	return out
}
