//go:build generate

// Package apis contains the API type definitions for the Slack provider.
//
//go:generate go run -tags generate sigs.k8s.io/controller-tools/cmd/controller-gen object:headerFile=../hack/boilerplate.go.txt paths=./...
//go:generate go run -tags generate github.com/crossplane/crossplane-tools/cmd/angryjet generate-methodsets --header-file=../hack/boilerplate.go.txt ./...
//go:generate go run -tags generate sigs.k8s.io/controller-tools/cmd/controller-gen crd:crdVersions=v1 output:artifacts:config=../package/family/crds paths=./v1alpha1/...
//go:generate go run -tags generate sigs.k8s.io/controller-tools/cmd/controller-gen crd:crdVersions=v1 output:artifacts:config=../package/conversation/crds paths=./conversation/... paths=./bookmark/... paths=./pin/...
//go:generate go run -tags generate sigs.k8s.io/controller-tools/cmd/controller-gen crd:crdVersions=v1 output:artifacts:config=../package/usergroup/crds paths=./usergroup/... paths=./usergroupmembers/...
package apis
