//go:build !ignore_autogenerated

/*
Copyright 2024 Avodah Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserGroupMembers) DeepCopyInto(out *UserGroupMembers) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserGroupMembers.
func (in *UserGroupMembers) DeepCopy() *UserGroupMembers {
	if in == nil {
		return nil
	}
	out := new(UserGroupMembers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UserGroupMembers) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserGroupMembersList) DeepCopyInto(out *UserGroupMembersList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UserGroupMembers, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserGroupMembersList.
func (in *UserGroupMembersList) DeepCopy() *UserGroupMembersList {
	if in == nil {
		return nil
	}
	out := new(UserGroupMembersList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UserGroupMembersList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserGroupMembersObservation) DeepCopyInto(out *UserGroupMembersObservation) {
	*out = *in
	if in.ResolvedUserIds != nil {
		in, out := &in.ResolvedUserIds, &out.ResolvedUserIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserGroupMembersObservation.
func (in *UserGroupMembersObservation) DeepCopy() *UserGroupMembersObservation {
	if in == nil {
		return nil
	}
	out := new(UserGroupMembersObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserGroupMembersParameters) DeepCopyInto(out *UserGroupMembersParameters) {
	*out = *in
	if in.UserGroupID != nil {
		in, out := &in.UserGroupID, &out.UserGroupID
		*out = new(string)
		**out = **in
	}
	if in.UserGroupRef != nil {
		in, out := &in.UserGroupRef, &out.UserGroupRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.UserGroupSelector != nil {
		in, out := &in.UserGroupSelector, &out.UserGroupSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.UserEmails != nil {
		in, out := &in.UserEmails, &out.UserEmails
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserGroupMembersParameters.
func (in *UserGroupMembersParameters) DeepCopy() *UserGroupMembersParameters {
	if in == nil {
		return nil
	}
	out := new(UserGroupMembersParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserGroupMembersSpec) DeepCopyInto(out *UserGroupMembersSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserGroupMembersSpec.
func (in *UserGroupMembersSpec) DeepCopy() *UserGroupMembersSpec {
	if in == nil {
		return nil
	}
	out := new(UserGroupMembersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserGroupMembersStatus) DeepCopyInto(out *UserGroupMembersStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserGroupMembersStatus.
func (in *UserGroupMembersStatus) DeepCopy() *UserGroupMembersStatus {
	if in == nil {
		return nil
	}
	out := new(UserGroupMembersStatus)
	in.DeepCopyInto(out)
	return out
}
